name: Welcome

on:
  issues:
    types:
      - opened

permissions:
  contents: read

jobs:
  greeting:
    permissions:
      issues: write  # for actions/first-interaction to comment on first issue
      pull-requests: write  # for actions/first-interaction to comment on first PR
    runs-on: cx-public-ubuntu-x64
    steps:
      - uses: actions/first-interaction@bd33205aa5c96838e10fd65df0d01efd613677c1 # v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thanks for submitting your first issue, we will have a look as quickly as possible.'
          pr-message: 'Thanks so much for your contribution, really appreciated! We will have a look and merge it if everything checks out!'
